"""Second independent re-audit probes as HTTP/DB tests.

Oracles are the auditor's, written before the run, with one correction: f_width_80mm named a
non-existent product (PRD-RP-310); the catalog's BluePrint 80 is PRD-PRN-320. Same strict
check as the first matrix: NO_CHANGE also forbids any attempted mutation tool call; `read` marks
a plain recommendation request, which needs no refusal notice.
"""

import pytest

from tests.test_reaudit_matrix import NO_CHANGE, check_variant, safe

CASES = [
    ('p_total_bedel', 'Q-1002', 'Toplam bedel 9.000 TL altında, 2 adet BlueScan Air ekle.', NO_CHANGE, {}),
    ('p_total_ikisine', 'Q-1002', 'İkisine 9.000 TL ayırdım, 2 adet BlueScan Air ekle.', NO_CHANGE, {}),
    ('p_total_hesap', 'Q-1002', 'Hesabın tamamı 9.000 TL altında olsun, 2 adet BlueScan Air ekle.', NO_CHANGE, {}),
    ('p_total_masraf', 'Q-1002', 'Masrafım en fazla 9.000 TL, 2 adet BlueScan Air ekle.', NO_CHANGE, {}),
    ('p_total_odeyecegim', 'Q-1002', 'En fazla 9.000 TL ödeyeceğim, 2 adet BlueScan Air ekle.', NO_CHANGE, {}),
    ('p_unit_tek', 'Q-1002', 'Tek ürünün birim fiyatı 9.000 TL altında, 2 adet BlueScan Air ekle.', {'PRD-BC-110': 2}, {}),
    ('p_unit_tanebasi', 'Q-1002', 'Tane başına 9.000 TL altında, 2 adet BlueScan Air ekle.', {'PRD-BC-110': 2}, {}),
    ('p_unit_herbiri', 'Q-1002', 'Her biri 9.000 TL altında, 2 adet BlueScan Air ekle.', {'PRD-BC-110': 2}, {}),
    ('p_unit_and_total', 'Q-1002', 'Birim fiyatı 9.000 TL altında olsun; sepet toplamı da 9.000 TL altında kalsın; 2 adet BlueScan Air ekle.', NO_CHANGE, {}),
    ('p_total_and_unit', 'Q-1002', 'Toplam en fazla 9.000 TL; birim fiyatı 9.000 TL altında 2 adet BlueScan Air ekle.', NO_CHANGE, {}),
    ('p_item_tutar', 'Q-1002', "BlueScan Air'in tutarı 9.000 TL altında ise 1 adet ekle.", safe({'PRD-BC-110': 1}), {}),
    ('p_unit_tutar', 'Q-1002', 'Birim tutarı 9.000 TL altında BlueScan Air 2 adet ekle.', {'PRD-BC-110': 2}, {}),
    ('p_item_fiyat_tutar', 'Q-1002', 'BlueScan Air ürününün fiyat tutarı 9.000 TL altında 1 adet ekle.', {'PRD-BC-110': 1}, {}),
    ('p_year_context', 'Q-1002', '2026 kampanyası için BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle.', {'PRD-BC-110': 1}, {}),
    ('p_year_bound', 'Q-1002', '2026 yılında BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle.', {'PRD-BC-110': 1}, {}),
    ('p_model_note', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; referans model numarası 2026.', safe({'PRD-BC-110': 1}), {}),
    ('p_second_500_write', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; limitim 500.', NO_CHANGE, {}),
    ('p_second_500_read', 'Q-1002', 'BlueScan Air 8.500 TL altında öner; limitim 500.', NO_CHANGE, {'no_recommendations': True}),
    ('p_second_written', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; bütçem beş yüz.', NO_CHANGE, {}),
    ('p_second_500_currency', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; limitim 500 lira.', NO_CHANGE, {}),
    ('p_budget_read_multi', 'Q-1002', 'Bütçem 9.000 TL, 2 adet BlueScan Air öner.', NO_CHANGE, {'no_recommendations': True}),
    ('p_budget_read_one', 'Q-1002', 'Bütçem 9.000 TL, 1 adet BlueScan Air öner.', NO_CHANGE, {'read': True}),
    ('p_budget_read_low', 'Q-1002', 'Bütçem 5.000 TL, BlueScan Air öner.', NO_CHANGE, {'no_recommendations': True, 'read': True}),
    ('p_unit_and_budget', 'Q-1002', 'Birim fiyatı 9.000 TL altında; bütçem 9.000 TL; 2 adet BlueScan Air ekle.', NO_CHANGE, {}),
    ('p_same_unit_two_formats', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; birim tavan 8500 TL.', {'PRD-BC-110': 1}, {}),
    ('p_currency_note', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; para birimi Türk lirası.', {'PRD-BC-110': 1}, {}),
    ('q_single_inner_suffix', 'Q-1002', "'BlueScan Air'i 1 adet ekle' ifadesini açıklar mısın?", NO_CHANGE, {}),
    ('q_single_inner_suffix_policy', 'Q-1002', "'BlueScan Air'i 1 adet ekle' ifadesi iade açısından ne yapar?", NO_CHANGE, {}),
    ('q_curly_inner_suffix', 'Q-1002', "‘BlueScan Air'i 1 adet ekle’ ifadesini açıklar mısın?", NO_CHANGE, {}),
    ('q_unclosed_double', 'Q-1002', 'Örnek metin: "BlueScan Air 1 adet ekle. Bu ifadenin açıklaması nedir?', NO_CHANGE, {}),
    ('q_unclosed_single', 'Q-1002', "Örnek metin: 'BlueScan Air 1 adet ekle. Bu ifadenin açıklaması nedir?", NO_CHANGE, {}),
    ('q_nested_double', 'Q-1002', '"BlueScan Air 1 adet ekle ve \'GreenScan Eco ekle\' ifadesini açıkla" cümlesini yorumla.', NO_CHANGE, {}),
    ('q_nested_single', 'Q-1002', '\'BlueScan Air 1 adet ekle ve "GreenScan Eco ekle" ifadesini açıkla\' cümlesini yorumla.', NO_CHANGE, {}),
    ('q_backtick_suffix', 'Q-1002', "`BlueScan Air'i 1 adet ekle` ifadesini açıklar mısın?", NO_CHANGE, {}),
    ('q_suffix_direct', 'Q-1002', "BlueScan Air'den 1 adet ekle.", {'PRD-BC-110': 1}, {}),
    ('q_quoted_name_direct', 'Q-1002', "'BlueScan Air' ürününden 1 adet ekle.", {'PRD-BC-110': 1}, {}),
    ('q_curly_name_direct', 'Q-1002', '‘BlueScan Air’ 1 adet ekle.', {'PRD-BC-110': 1}, {}),
    ('q_command_then_outside', 'Q-1002', 'Örnekte "GreenScan Eco 2 adet ekle" yazıyor. BlueScan Air 1 adet ekle.', {'PRD-BC-110': 1}, {}),
    ('q_outside_then_example', 'Q-1002', 'BlueScan Air 1 adet ekle. Örnekte "GreenScan Eco 2 adet ekle" yazıyor.', {'PRD-BC-110': 1}, {}),
    ('q_product_example', 'Q-1002', '"GreenScan Eco 1D Kablosuz Okuyucu" örnek üründür. BlueScan Air 1 adet ekle.', safe({'PRD-BC-110': 1}), {}),
    ('q_product_example_and', 'Q-1002', 'Örnek ürün "GreenScan Eco 1D Kablosuz Okuyucu" ve BlueScan Air 1 adet ekle.', safe({'PRD-BC-110': 1}), {}),
    ('q_description_example', 'Q-1002', '"2 adet" örnek miktardır; BlueScan Air 1 adet ekle.', safe({'PRD-BC-110': 1}), {}),
    ('q_outside_total', 'Q-1001', 'Örnekte "GreenScan Eco ekle" yazıyor. BlueScan Air toplam 4 adet olsun.', {'PRD-BC-110': 4}, {}),
    ('q_unapproved', 'Q-1002', 'Onay vermedim, BlueScan Air 1 adet ekle.', NO_CHANGE, {}),
    ('q_later_approval', 'Q-1002', 'BlueScan Air 1 adet ekle; önce onayımı almalısın.', NO_CHANGE, {}),
    ('q_already_approved', 'Q-1002', 'Onayımı verdim; BlueScan Air 1 adet ekle.', {'PRD-BC-110': 1}, {}),
    ('n_mixed_bare', 'Q-1002', 'BlueScan Air 1 adet ve GreenScan Eco 2 ekle.', safe({'PRD-BC-110': 1, 'PRD-BC-140': 2}), {}),
    ('n_mixed_2x', 'Q-1002', 'BlueScan Air 1 adet ve GreenScan Eco 2x ekle.', safe({'PRD-BC-110': 1, 'PRD-BC-140': 2}), {}),
    ('n_mixed_reverse', 'Q-1002', 'BlueScan Air 2 ekle ve GreenScan Eco 1 adet ekle.', safe({'PRD-BC-110': 2, 'PRD-BC-140': 1}), {}),
    ('n_same_bound', 'Q-1002', 'BlueScan Air 2 adet ve GreenScan Eco 2 adet ekle.', {'PRD-BC-110': 2, 'PRD-BC-140': 2}, {}),
    ('n_different_bound', 'Q-1002', 'BlueScan Air 1 adet ve GreenScan Eco 2 adet ekle.', safe({'PRD-BC-110': 1, 'PRD-BC-140': 2}), {}),
    ('n_percent', 'Q-1002', 'BlueScan Air ekle; yüzde 7 partner indirimini göster.', {'PRD-BC-110': 1}, {}),
    ('n_percent_symbol', 'Q-1002', 'BlueScan Air ekle; %7 partner indirimini göster.', {'PRD-BC-110': 1}, {}),
    ('n_percent_bound_qty', 'Q-1002', 'BlueScan Air 3 adet ekle; %7 partner indirimini göster.', {'PRD-BC-110': 3}, {}),
    ('n_year_unbound', 'Q-1002', '2026 kampanyası için BlueScan Air ekle.', {'PRD-BC-110': 1}, {}),
    ('n_date', 'Q-1002', '23.09.2026 tarihi için BlueScan Air ekle.', {'PRD-BC-110': 1}, {}),
    ('n_year_bound', 'Q-1002', '2026 yılı için BlueScan Air ekle.', {'PRD-BC-110': 1}, {}),
    ('n_days', 'Q-1002', '2 gün içinde kullanılacak BlueScan Air ekle.', {'PRD-BC-110': 1}, {}),
    ('n_print_model', 'Q-1002', 'BluePrint 80 ekle.', {'PRD-PRN-320': 1}, {}),
    ('n_print_80mm', 'Q-1002', '80 mm BluePrint 80 ekle.', {'PRD-PRN-320': 1}, {}),
    ('n_print_wrong_width', 'Q-1002', '58 mm genişliğinde BluePrint 80 ekle.', NO_CHANGE, {}),
    ('n_print_model_number', 'Q-1002', 'Model numarası 80 olan BluePrint 80 ekle.', {'PRD-PRN-320': 1}, {}),
    ('n_fullwidth_mixed', 'Q-1002', 'BlueScan Air １ adet ve GreenScan Eco ２ ekle.', safe({'PRD-BC-110': 1, 'PRD-BC-140': 2}), {}),
    ('n_update_bare', 'Q-1001', 'BlueScan Air miktarını 3 güncelle.', NO_CHANGE, {}),
    ('n_signed_bound', 'Q-1002', 'BlueScan Air - 3 adet ekle.', NO_CHANGE, {}),
    ('n_fraction_bound', 'Q-1002', 'BlueScan Air 3 / 4 adet ekle.', NO_CHANGE, {}),
    ('n_more_signed', 'Q-1001', 'BlueScan Air - 1 adet daha ekle.', NO_CHANGE, {}),
    ('n_product_license', 'Q-1002', 'BlueStock Pro Lisans 12 Ay ekle.', {'PRD-SW-520': 1}, {}),
    ('x_reverse_qr', 'Q-1001', "QR'lı GreenScan Eco ile BlueScan Air ürününü değiştir.", NO_CHANGE, {}),
    ('x_reverse_late_qr', 'Q-1001', 'GreenScan Eco ile BlueScan Air ürününü değiştir, hedef QR desteklesin.', NO_CHANGE, {}),
    ('x_reverse_late_2d', 'Q-1004', "GreenScan Eco ile BlueScan Pro'yu değiştir. Yeni ürün 2D olmalı.", NO_CHANGE, {}),
    ('x_reverse_late_semicolon', 'Q-1004', "GreenScan Eco ile BlueScan Pro'yu değiştir; yeni ürün 2D olmalı.", NO_CHANGE, {}),
    ('x_late_qr_source_first', 'Q-1001', 'BlueScan Air ürününü GreenScan Eco ile değiştir, hedef QR desteklesin.', NO_CHANGE, {}),
    ('x_source_postpositive', 'Q-1001', "QR destekleyen BlueScan Air'i GreenScan Eco ile değiştir.", {'PRD-BC-140': 1}, {}),
    ('x_source_after_name', 'Q-1001', "BlueScan Air QR'lı ürününü GreenScan Eco ile değiştir.", {'PRD-BC-140': 1}, {}),
    ('x_source_before_target', 'Q-1001', "QR'lı BlueScan Air'i kablosuz GreenScan Eco ile değiştir.", {'PRD-BC-140': 1}, {}),
    ('x_reverse_source_feature', 'Q-1001', "GreenScan Eco ile QR'lı BlueScan Air'i değiştir.", {'PRD-BC-140': 1}, {}),
    ('x_both_features', 'Q-1001', "Kablosuz GreenScan Eco ile QR'lı BlueScan Air'i değiştir.", {'PRD-BC-140': 1}, {}),
    ('x_target_compatible', 'Q-1004', "BlueScan Pro'yu QR'lı BlueScan Air ile değiştir.", {'PRD-BC-110': 1}, {}),
    ('x_target_compatible_reversed', 'Q-1004', "QR'lı BlueScan Air ile 2D BlueScan Pro'yu değiştir.", {'PRD-BC-110': 1}, {}),
    ('x_yerine_only', 'Q-1001', "QR'lı BlueScan Air yerine GreenScan Eco ekle.", safe({'PRD-BC-140': 1}), {}),
    ('x_yerine_explicit', 'Q-1001', "BlueScan Air yerine QR'lı GreenScan Eco ekle, değiştir.", NO_CHANGE, {}),
    ('x_stoklu_target_qr', 'Q-1001', "BlueScan Air'i stoklu QR'lı GreenScan Eco ile değiştir.", NO_CHANGE, {}),
    ('x_source_semicolon', 'Q-1001', "QR'lı BlueScan Air ürününü değiştir; GreenScan Eco olsun.", {'PRD-BC-140': 1}, {}),
    ('x_plus_reverse_late', 'Q-2001', 'GreenScan Eco Plus ile BlueScan Air Plus ürününü değiştir, QR zorunlu.', NO_CHANGE, {}),
    ('x_id_target_late', 'Q-1001', 'PRD-BC-140 ile PRD-BC-110 ürününü değiştir, hedef QR olmalı.', NO_CHANGE, {}),
    ('c_comma_question', 'Q-1002', "BlueScan Air 1 adet ekle, GreenScan Eco'nun fiyatı ne?", safe({'PRD-BC-110': 1}), {}),
    ('c_period_question', 'Q-1002', "BlueScan Air 1 adet ekle. GreenScan Eco'nun fiyatı ne?", safe({'PRD-BC-110': 1}), {}),
    ('c_semicolon_question', 'Q-1002', "BlueScan Air 1 adet ekle; GreenScan Eco'nun fiyatı ne?", safe({'PRD-BC-110': 1}), {}),
    ('c_and_question', 'Q-1002', "BlueScan Air 1 adet ekle ve GreenScan Eco'nun fiyatı ne?", safe({'PRD-BC-110': 1}), {}),
    ('c_and_stock_question', 'Q-1002', 'BlueScan Air 1 adet ekle ve GreenScan Eco stokta mı?', safe({'PRD-BC-110': 1}), {}),
    ('c_same_product_question', 'Q-1002', "BlueScan Air 1 adet ekle ve BlueScan Air'in fiyatı ne?", safe({'PRD-BC-110': 1}), {}),
    ('c_shared_verb', 'Q-1002', 'BlueScan Air ve GreenScan Eco 1 adet ekle.', {'PRD-BC-110': 1, 'PRD-BC-140': 1}, {}),
    ('c_two_verbs_comma', 'Q-1002', 'BlueScan Air 1 adet ekle, GreenScan Eco 1 adet ekle.', safe({'PRD-BC-110': 1, 'PRD-BC-140': 1}), {}),
    ('c_two_verbs_period', 'Q-1002', 'BlueScan Air 1 adet ekle. GreenScan Eco 1 adet ekle.', safe({'PRD-BC-110': 1, 'PRD-BC-140': 1}), {}),
    ('c_two_verbs_semicolon', 'Q-1002', 'BlueScan Air 1 adet ekle; GreenScan Eco 1 adet ekle.', {'PRD-BC-110': 1, 'PRD-BC-140': 1}, {}),
    ('c_negative_feature_comma', 'Q-1002', 'QR zorunlu, BlueScan Lite 1 adet ekle.', NO_CHANGE, {}),
    ('c_negative_feature_period', 'Q-1002', 'QR zorunlu. BlueScan Lite 1 adet ekle.', NO_CHANGE, {}),
    ('c_feature_all', 'Q-1002', 'QR zorunlu; BlueScan Air ve GreenScan Eco 1 adet ekle.', NO_CHANGE, {}),
    ('c_feature_separate', 'Q-1002', 'BlueScan Air 1 adet ekle; QR zorunlu; GreenScan Eco 1 adet ekle.', {'PRD-BC-110': 1, 'PRD-BC-140': 1}, {}),
    ('c_note_and', 'Q-1002', 'BlueScan Air 1 adet ekle ve not: müşteri öğleden sonra gelecek.', {'PRD-BC-110': 1}, {}),
    ('c_product_note_and', 'Q-1002', 'BlueScan Air 1 adet ekle ve not: GreenScan Eco müşterinin mevcut cihazı.', safe({'PRD-BC-110': 1}), {}),
    ('c_product_note_period', 'Q-1002', 'BlueScan Air 1 adet ekle. Not: GreenScan Eco müşterinin mevcut cihazı.', safe({'PRD-BC-110': 1}), {}),
    ('c_golden8', 'Q-1002', 'Sahada internet olmayacak; 4G el terminali ve offline senkron için gerekli lisansı ekle.', {'PRD-POS-210': 1, 'PRD-SW-520': 1}, {}),
    ('c_golden11', 'Q-1002', 'Depo için 3 adet BlueScan Air ekle; partner indirimini göster.', {'PRD-BC-110': 3}, {}),
    ('c_golden12', 'Q-1002', '1.500 TL altında stoklu koruyucu kılıf ekle ve kaynağını göster.', {'PRD-ACC-710': 1}, {}),
    ('c_golden17', 'Q-1002', 'Offline senkron ve şube senkronu için gerekli yazılımları ekle.', {'PRD-SW-520': 1, 'PRD-SW-530': 1}, {}),
    ('s_tukenmis', 'Q-1002', 'Stokları tükenmiş ürünleri bekleyebilir miyiz?', NO_CHANGE, {'knowledge': 'KNE-STOCK-001'}),
    ('s_bitti', 'Q-1002', 'Stok bittiğinde sipariş verebilir miyim?', NO_CHANGE, {'knowledge': 'KNE-STOCK-001'}),
    ('s_kalmayan', 'Q-1002', 'Stoğu kalmayan ürünü beklemek mümkün mü?', NO_CHANGE, {'knowledge': 'KNE-STOCK-001'}),
    ('s_mevcut_degil', 'Q-1002', 'Stokta mevcut değilse bekleme koşulları nedir?', NO_CHANGE, {'knowledge': 'KNE-STOCK-001'}),
    ('s_stok_yok', 'Q-1002', 'Stok yoksa sipariş nasıl ilerler?', NO_CHANGE, {'knowledge': 'KNE-STOCK-001'}),
    ('s_bekleme_permission', 'Q-1002', 'Bekleme onayını nasıl vermeliyim?', NO_CHANGE, {'knowledge': 'KNE-STOCK-001'}),
    ('s_delivery_hazir', 'Q-1002', 'Stokta hazır donanımlar kaç günde teslim edilir?', NO_CHANGE, {'knowledge': 'KNE-SHIP-001'}),
    ('s_delivery_wait', 'Q-1002', 'Stokta olan donanımlarda teslimatı ne kadar bekleyeceğim?', NO_CHANGE, {'knowledge': 'KNE-SHIP-001'}),
    ('s_two_policies', 'Q-1002', 'Stoğu tükenen ürünlerde bekleme ve iade politikası nedir?', NO_CHANGE, {'knowledge': 'KNE-STOCK-001'}),
    ('s_named_absent', 'Q-1002', 'RedScan Mini stokta yoksa sipariş nasıl olur?', NO_CHANGE, {'knowledge': 'KNE-STOCK-001'}),
    ('f_limit_dot', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; limitim 5000.', NO_CHANGE, {}),
    ('f_limit_no_dot', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; limitim 5000', NO_CHANGE, {}),
    ('f_limit_grouped_dot', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; limitim 5.000.', NO_CHANGE, {}),
    ('f_limit_currency', 'Q-1002', 'BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle; limitim 5.000 TL.', NO_CHANGE, {}),
    ('f_limit_read_dot', 'Q-1002', 'BlueScan Air 8.500 TL altında öner; limitim 5.000.', NO_CHANGE, {'no_recommendations': True}),
    ('f_width_58mm', 'Q-1002', '58mm genişliğinde BluePrint 80 ekle.', NO_CHANGE, {}),
    ('f_width_80mm', 'Q-1002', '80mm genişliğinde BluePrint 80 ekle.', {'PRD-PRN-320': 1}, {}),
    ('f_yerine_no_feature', 'Q-1001', 'BlueScan Air yerine GreenScan Eco ekle.', safe({'PRD-BC-140': 1}), {}),
    ('f_yerine_reverse', 'Q-1001', "GreenScan Eco ekle, QR'lı BlueScan Air yerine.", safe({'PRD-BC-140': 1}), {}),
]


@pytest.mark.parametrize("case,quote,text,expected,options", CASES, ids=[c[0] for c in CASES])
async def test_reaudit2_variant(db, case, quote, text, expected, options):
    await check_variant(db, quote, text, expected, **options)


# Own probes beyond the audit, per finding class: the fix must hold for the class, not one sentence.
OWN_PROBES = [
    ("own_price_en_fazla", "Q-1002", "BlueScan Air 8.500 TL altında 1 adet ekle; en fazla 500.", NO_CHANGE, {}),
    ("own_price_bin_word", "Q-1002", "BlueScan Air 8.500 TL altında 1 adet ekle, bütçem de 5 bin.", NO_CHANGE, {}),
    ("own_price_suffix_below", "Q-1002", "BlueScan Air 8.500 TL altında 1 adet ekle; 500'ün altında olsun.", NO_CHANGE, {}),
    ("own_price_read_tavan", "Q-1002", "BlueScan Air 8.500 TL altında öner; tavanım 5.000.", NO_CHANGE, {"no_recommendations": True}),
    ("own_price_unit_and_spend", "Q-1002", "Tane başına 9.000 TL altında; harcamam 9.000 TL; 2 adet BlueScan Air ekle.", NO_CHANGE, {}),
    ("own_price_article_bir", "Q-1002", "1.500 TL altında bir koruyucu kılıf ekle.", {"PRD-ACC-710": 1}, {}),
    ("own_price_year_bound", "Q-1002", "2026 yılı için BlueScan Air birim fiyatı 8.500 TL altında 1 adet ekle.", {"PRD-BC-110": 1}, {}),
    ("own_quote_backtick_suffix", "Q-1002", "`BlueScan Air'i 1 adet ekle` ne anlama gelir?", NO_CHANGE, {}),
    ("own_quote_unclosed_guillemet", "Q-1002", "«BlueScan Air 1 adet ekle ifadesi nedir?", NO_CHANGE, {}),
    ("own_quote_suffix_closed_name", "Q-1002", "'BlueScan Air'ı 1 adet ekle.", {"PRD-BC-110": 1}, {}),
    ("own_quote_outside_update", "Q-1001", 'Örnekte "GreenScan Eco ekle" yazıyor; BlueScan Air miktarını 3 adede güncelle.', {"PRD-BC-110": 3}, {}),
    ("own_approval_future", "Q-1002", "BlueScan Air 1 adet ekle; önce müdürden onay alacağım.", NO_CHANGE, {}),
    ("own_approval_consult", "Q-1002", "BlueScan Air 1 adet ekle ama önce bana danış.", NO_CHANGE, {}),
    ("own_approval_granted_passive", "Q-1002", "Onaylandı, BlueScan Air 1 adet ekle.", {"PRD-BC-110": 1}, {}),
    ("own_scope_note_colon", "Q-1002", 'Not: "GreenScan Eco" müşteride var, BlueScan Air 1 adet ekle.', NO_CHANGE, {}),
    ("own_scope_note_sentence", "Q-1002", "BlueScan Air 1 adet ekle. Müşteride GreenScan Eco zaten var.", NO_CHANGE, {}),
    ("own_scope_ile_pair", "Q-1002", "GreenScan Eco ile BlueScan Air ekle.", NO_CHANGE, {}),
    ("own_scope_context_pair", "Q-1002", "Depo için BlueScan Air ve GreenScan Eco 1 adet ekle.", {"PRD-BC-110": 1, "PRD-BC-140": 1}, {}),
    ("own_scope_two_sentences", "Q-1002", "BlueScan Air 1 adet ekle. GreenScan Eco 1 adet ekle.", {"PRD-BC-110": 1, "PRD-BC-140": 1}, {}),
    ("own_yerine_target_feature", "Q-1001", "BlueScan Air yerine QR'lı GreenScan Eco ekle.", NO_CHANGE, {}),
    ("own_yerine_object_first", "Q-1001", "GreenScan Eco'yu BlueScan Air yerine ekle.", NO_CHANGE, {}),
    ("own_qty_mixed_larger", "Q-1002", "BlueScan Air 3 adet ve GreenScan Eco 5 ekle.", NO_CHANGE, {}),
    ("own_qty_percent_question", "Q-1002", "BlueScan Air ekle; %10 indirim var mı?", {"PRD-BC-110": 1}, {}),
    ("own_qty_date_bound", "Q-1002", "01.10.2026 tarihinde teslim için BlueScan Air 2 adet ekle.", {"PRD-BC-110": 2}, {}),
    ("own_size_58_category", "Q-1002", "58 mm fiş yazıcı ekle.", {"PRD-PRN-310": 1}, {}),
    ("own_size_80_category", "Q-1002", "80 mm fiş yazıcı ekle.", {"PRD-PRN-320": 1}, {}),
    ("own_size_dpi_mismatch", "Q-1002", "203 dpi BluePrint 80 ekle.", NO_CHANGE, {}),
    ("own_target_late_comma_2d", "Q-1004", "GreenScan Eco ile BlueScan Pro ürününü değiştir, yeni ürün 2D olsun.", NO_CHANGE, {}),
    ("own_target_preface", "Q-1001", "QR zorunlu, BlueScan Air'i GreenScan Eco ile değiştir.", NO_CHANGE, {}),
    ("own_target_late_ok", "Q-1001", "GreenScan Eco ile BlueScan Air ürününü değiştir, hedef kablosuz olsun.", {"PRD-BC-140": 1}, {}),
    ("own_source_post_features", "Q-1004", "BlueScan Pro rugged 2D ürününü GreenScan Eco ile değiştir.", {"PRD-BC-140": 1}, {}),
    ("own_source_supported_by", "Q-1001", "QR destekleyen BlueScan Air'i GreenScan Eco ile değiştir.", {"PRD-BC-140": 1}, {}),
]


@pytest.mark.parametrize("case,quote,text,expected,options", OWN_PROBES, ids=[c[0] for c in OWN_PROBES])
async def test_own_probe(db, case, quote, text, expected, options):
    await check_variant(db, quote, text, expected, **options)
