"""initial schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bootstrap_state",
        sa.Column("seed_id", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("seed_id", name=op.f("pk_bootstrap_state")),
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("segment", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("price_tier", sa.Text(), nullable=False),
        sa.Column("credit_limit_try", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("allow_backorder", sa.Boolean(), nullable=False),
        sa.Column("default_locale", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.CheckConstraint("credit_limit_try >= 0", name=op.f("ck_customers_credit_nonnegative")),
        sa.PrimaryKeyConstraint("customer_id", name=op.f("pk_customers")),
    )
    op.create_table(
        "knowledge_entries",
        sa.Column("knowledge_id", sa.Text(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("locale", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "applies_to",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("knowledge_id", name=op.f("pk_knowledge_entries")),
    )
    op.create_table(
        "price_rules",
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("condition", sa.Text(), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.CheckConstraint(
            "discount_percent >= 0 AND discount_percent <= 100",
            name=op.f("ck_price_rules_discount_range"),
        ),
        sa.PrimaryKeyConstraint("rule_id", name=op.f("pk_price_rules")),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("sku", sa.Text(), nullable=False),
        sa.Column("name_tr", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=False),
        sa.Column("price_try", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("stock_qty", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("min_order_qty", sa.Integer(), nullable=False),
        sa.Column("delivery_days", sa.Integer(), nullable=False),
        sa.Column("warranty_months", sa.Integer(), nullable=False),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "aliases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "substitute_product_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "delivery_days >= 0 AND warranty_months >= 0",
            name=op.f("ck_products_durations_nonnegative"),
        ),
        sa.CheckConstraint("min_order_qty > 0", name=op.f("ck_products_min_order_positive")),
        sa.CheckConstraint("price_try >= 0", name=op.f("ck_products_price_nonnegative")),
        sa.CheckConstraint("stock_qty >= 0", name=op.f("ck_products_stock_nonnegative")),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_table(
        "quotes",
        sa.Column("quote_id", sa.Text(), nullable=False),
        sa.Column("customer_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by_channel", sa.Text(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_quotes_version_positive")),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.customer_id"], name=op.f("fk_quotes_customer_id_customers")
        ),
        sa.PrimaryKeyConstraint("quote_id", name=op.f("pk_quotes")),
        sa.UniqueConstraint("quote_id", "customer_id", name=op.f("uq_quotes_quote_id")),
    )
    op.create_table(
        "chat_sessions",
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("customer_id", sa.Text(), nullable=False),
        sa.Column("quote_id", sa.Text(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("locale", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quote_id", "customer_id"],
            ["quotes.quote_id", "quotes.customer_id"],
            name=op.f("fk_chat_sessions_quote_id_quotes"),
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_chat_sessions")),
    )
    op.create_table(
        "quote_items",
        sa.Column("quote_item_id", sa.Text(), nullable=False),
        sa.Column("quote_id", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_try", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source_message_id", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("fulfillment_status", sa.Text(), server_default="in_stock", nullable=False),
        sa.Column("replaced_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fulfillment_status IN ('in_stock','backorder','out_of_stock')",
            name=op.f("ck_quote_items_fulfillment_valid"),
        ),
        sa.CheckConstraint(
            "quantity >= 0 AND (status != 'active' OR quantity > 0)",
            name=op.f("ck_quote_items_quantity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active','removed','replaced')", name=op.f("ck_quote_items_status_valid")
        ),
        sa.CheckConstraint(
            "replaced_by IS NULL OR replaced_by != quote_item_id",
            name=op.f("ck_quote_items_replacement_not_self"),
        ),
        sa.CheckConstraint("unit_price_try >= 0", name=op.f("ck_quote_items_price_nonnegative")),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.product_id"], name=op.f("fk_quote_items_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.quote_id"], name=op.f("fk_quote_items_quote_id_quotes")
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by"],
            ["quote_items.quote_item_id"],
            name=op.f("fk_quote_items_replaced_by_quote_items"),
        ),
        sa.PrimaryKeyConstraint("quote_item_id", name=op.f("pk_quote_items")),
    )
    op.create_index(
        "uq_quote_active_product",
        "quote_items",
        ["quote_id", "product_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column(
            "trusted_constraints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "persisted_plan",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("final_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','completed','failed')",
            name=op.f("ck_chat_messages_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.session_id"],
            name=op.f("fk_chat_messages_session_id_chat_sessions"),
        ),
        sa.PrimaryKeyConstraint("session_id", "message_id", name=op.f("pk_chat_messages")),
    )
    op.create_table(
        "mutation_receipts",
        sa.Column("quote_id", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("action_index", sa.Integer(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column(
            "before",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "after",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("committed_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operation IN ('add_to_quote','update_quote_item','replace_with_alternative')",
            name=op.f("ck_mutation_receipts_operation_valid"),
        ),
        sa.CheckConstraint(
            "action_index >= 0 AND committed_version > 0",
            name=op.f("ck_mutation_receipts_index_version_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.quote_id"], name=op.f("fk_mutation_receipts_quote_id_quotes")
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "message_id"],
            ["chat_messages.session_id", "chat_messages.message_id"],
            name=op.f("fk_mutation_receipts_session_id_chat_messages"),
        ),
        sa.PrimaryKeyConstraint("quote_id", "idempotency_key", name=op.f("pk_mutation_receipts")),
    )
    op.create_table(
        "tool_call_logs",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("attempt_id", sa.Text(), nullable=False),
        sa.Column("tool_sequence", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column(
            "input",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "output",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "sources",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("replayed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "mutation_applied", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tool_name IN ('search_products', 'get_knowledge_entries', 'get_quote', 'add_to_quote', 'update_quote_item', 'replace_with_alternative')",
            name=op.f("ck_tool_call_logs_tool_valid"),
        ),
        sa.CheckConstraint(
            "NOT (replayed AND mutation_applied)",
            name=op.f("ck_tool_call_logs_replay_has_no_mutation"),
        ),
        sa.CheckConstraint(
            "tool_sequence > 0 AND duration_ms >= 0",
            name=op.f("ck_tool_call_logs_sequence_duration_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "message_id"],
            ["chat_messages.session_id", "chat_messages.message_id"],
            name=op.f("fk_tool_call_logs_session_id_chat_messages"),
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_tool_call_logs")),
        sa.UniqueConstraint(
            "session_id",
            "message_id",
            "attempt_id",
            "tool_sequence",
            name=op.f("uq_tool_call_logs_session_id"),
        ),
    )
    # ### end Alembic commands ###
    # Runtime role cannot create or alter schema; bootstrap metadata is read-only.
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON products, knowledge_entries, customers, price_rules, quotes, quote_items, chat_sessions, chat_messages, tool_call_logs, mutation_receipts TO tbr_runtime"
    )
    op.execute("GRANT SELECT ON bootstrap_state, alembic_version TO tbr_runtime")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO tbr_runtime")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool_call_logs")
    op.drop_table("mutation_receipts")
    op.drop_table("chat_messages")
    op.drop_index(
        "uq_quote_active_product",
        table_name="quote_items",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("quote_items")
    op.drop_table("chat_sessions")
    op.drop_table("quotes")
    op.drop_table("products")
    op.drop_table("price_rules")
    op.drop_table("knowledge_entries")
    op.drop_table("customers")
    op.drop_table("bootstrap_state")
    # ### end Alembic commands ###
